### ISSUE TITLE
Find Name for Project

### ISSUE THREAD

**Issue by baris-zongur-2016400285** [gumityolcu/CMPE487-Final#1]
Finding a name for the group and game.
Open to new ideas. 
LAN MortalCombat is off the table. 

DL - 30.12.2019

**Comment by gumityolcu** [comment]
No, the deadline is 30 December, please update.

**Comment by baris-zongur-2016400285** [comment]
Done.

**Comment by gumityolcu** [comment]
We decided on SHOW ME WHAT YOU GOT
